### ISSUE TITLE
[Task]: 付款单执行付款的细化处理

### ISSUE THREAD

**Issue by marchtian** [steedos-labs/feikongwang#129]
### SubTasks 子任务

一、付款审批前
- [x] 可以修改付款单及明细，可以删除
- [x] 可以发起审批
- [x] 付款状态、付款日期只读（不可修改）

二、付款审批时
- [x] 禁止编辑、删除付款单及明细

三、付款审批后
- [x] 禁止编辑、删除付款单及明细
- [ ] 审批如果通过，则对出纳人员（？）开放“付款”按钮
- [x] “付款”按钮的前台：录入付款日期、付款状态置为已支付
- [x] “付款”按钮的后台：（1）修改付款单的付款日期、付款状态 （2）根据付款单的明细，自动生成付款记录（作为合同的子表）

**Comment by lizheng-steedos** [comment]
关联任务：
- https://github.com/steedos/steedos-platform/issues/6235
