### ISSUE TITLE
[Task]: 客商对象增加“开票信息”和“邮寄信息”子表

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#137]
### SubTasks 子任务

- [x] -当前客商对象“开票信息”字段复制到“开票信息”子表中，同时去掉客商对象中开票信息字段；

- [x] 增加“邮寄信息”子表，字段参考：
<img width="946" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/05e555e5-3f06-4c2b-82cf-68be2d8521ff">

- [x] 这两个表分别加一个默认的勾选框字段，同一个客商下，每个子表只能有一条默认的记录；
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/deda3e99-e145-4881-b68a-85bf27f12ee9">

**Comment by lizheng-steedos** [comment]
- [ ] 字段调整
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/763e6419-2bfc-448d-a4e8-ca590b41e015">

- [ ] 列表视图、搜索项配置
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/0636b4fc-4bdc-4e64-b0d6-a7f23568bcff">
