### ISSUE TITLE
[Task]: 【合同开票明细】对象字段开发

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#143]
### SubTasks 子任务

- [x] 合同：只能选择主表中供应商签订的应收合同记录；（应收合同中客户字段值等于主表客户名称字段）；
- [x] 合同日期：日期类型字段；根据合同自动带出合同日期字段，只读；
- [x] 合同金额：金额类型字段；根据合同自动带出合同的金额字段，只读；
- [x] 合同已开票金额：金额类型字段；根据合同自动带出已开票金额字段，只读；
- [x] 合同剩余开票金额：金额类型字段；根据合同自动带剩余开票金额字段，只读；
- [x] 本次开票金额：用户自己填；
- [x] 保存记录校验：本次开票金额不得大于合同剩余开票金额，否则提示“本次开票金额不得大于合同剩余开票金额，请修改开票金额”，禁止用户提交。

**Comment by ysc1234** [comment]
为实现合同日期、合同金额、合同已开票金额、合同剩余开票金额、在新建编辑页让字段只读
目前方案：
  使用amis属性 "disabled": true,控制只读
 目前问题：合同日期、合同金额、合同已开票金额、合同剩余开票金额单元格还可以编辑
