### ISSUE TITLE
[Task]: 【合同收款明细】对象字段开发

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#144]
### SubTasks 子任务

- [x] 合同：只能选择主表中供应商签订的应收合同记录；（应收合同中客户字段值等于主表客户名称字段）；
- [x] 合同日期：日期类型字段；根据合同自动带出合同日期字段，只读；
- [x] 合同金额：金额类型字段；根据合同自动带出合同的金额字段，只读；
- [x] 合同应收金额：金额类型字段；根据合同自动带出合同的应收金额字段，只读；
- [x] 开票应收金额（暂不处理）
- [x] 提交记录时校验：收款金额+折让金额不得大于合同应收金额字段的值
