### ISSUE TITLE
[Task]: 【发票收款核销】对象新建记录开发逻辑

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#161]
### SubTasks 子任务

- [x] 合同：只读，根据主表合同收款明细对象中的合同自动带出；
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/99596c61-143c-40f5-87ff-a075c4f56fe5">

- [x] 开票： 必填，弹框值需要过滤，只显示合同对应的客户绑定的开票记录；

- [x] 发票应收金额：只读，根据选中的开票对象中的发票应收金额自动带出；
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/aaa0c538-bf09-4627-9e10-7a68ca87c718">
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/c7a10da0-8f6a-4f12-8483-89b3b4c364fc">

- [x] 剩余核销收款金额：只读，根据主表合同收款明细对象中的剩余收款金额自动带出；
- [x] 剩余核销折让金额：只读，根据主表合同收款明细对象中的剩余折让金额自动带出；
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/417ee0e5-8512-4ffb-95cd-2d2c7d0be490">

- [x] 禁止提交校验：
    - 本次核销收款金额>剩余核销收款金额：提示“本次核销收款金额超过剩余核销收款金额，请调整本次核销收款金额”
    - 本次核销折让金额>剩余核销折让金额：提示“本次核销折让金额超过剩余核销折让金额，请调整本次核销折让金额”

- [x] 隐藏发票记录详情页下发票收款核销相关表的新建按钮：
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/8b9948c9-8370-487e-9ea3-fb0518292cea">
