### ISSUE TITLE
[Task]: 【预收款】增加“核销”、“退款”按钮

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos-labs/feikongwang#171]
### SubTasks 子任务

- [x] 台账记录为“状态为已收款”并且预售款余额>0的情况下显示这两个按钮；
- [x] 隐藏子表“预收款核销明细”和“退款”表头的新建按钮；
<img width="1920" alt="image" src="https://github.com/steedos-labs/feikongwang/assets/151509384/b3e6c33d-75e5-4a77-bb3d-ea8d5e8eb0a8">

- [x] 原子表核销和退款新建功能调整为通过记录页右上角的“核销”和“退款”来实现；
  - 点击“核销”弹出核销新建的页面；
  - 点击“退款”弹出退款新建的页面；
