### ISSUE TITLE
[Task]: 客商、应收、应付、合同字段调整

### ISSUE THREAD

**Issue by ysc1234** [steedos-labs/feikongwang#34]
### SubTasks 子任务

 对照帐房管家修改字段

**Comment by chenzhipei** [comment]
应收：
- [x] 调整标签顺序：应收合同、客商、开票、收款
- [x] 应收合同列表视图显示字段调整：合同名称、合同编号、客户名称、合同日期、合同金额、合同应收
- [x] 应收合同新建字段调整：客户名称、合同名称、合同编号、合同标签、合同日期、合同金额、联系人、跟进人、部门
- [x] 应收合同添加子表：产品信息
- [x] 客商名称调整为客户管理
- [x] 客商列表视图字段调整：客户名称、客户编号、负责人、所属行业、客户性质
- [x] 客商新建字段调整：客户名称、客户编号、客户性质、所属行业、办公地址、负责人、赊销额度
- [x] 开票列表视图显示字段调整：客户编号、客户名称、税率、发票号码、开票日期、开票金额、税额、备注、开票方式、发票状态
- [x] 开票新建字段调整：客户名称、发票类型、税率、发票号码、发票代码、开票日期、关联合同、开票金额、税额
- [x] 开票新增子表：开票信息、邮寄信息
- [x] 收款列表视图显示字段调整：客户名称、客户编号、回款日期、回款金额、折让金额、核销金额、预收款、收款账户、单据编号、收入类型、备注、状态
- [x] 收款新建字段调整：客户名称、收款账户、回款日期、关联合同、回款金额、计入预收款、单据编号、收入类型、备注
