### ISSUE TITLE
[Task]: 应付，付款单等对象的部分字段，选择时需按照其他字段进行过滤/指定

### ISSUE THREAD

**Issue by marchtian** [steedos-labs/feikongwang#77]
### SubTasks 子任务

- [x] 付款单，“供应商收款账户”应依据所选的“供应商”来过滤
- [x] 付款单的付款记录，“合同”应依据已选定的“付款单”对应的“供应商”来过滤
- [ ] 应付合同的发票，新建时，应依据已选定的“应付合同”指定对应的“供应商、无需选择

**Comment by marchtian** [comment]
https://github.com/steedos-labs/feikongwang/issues/109

**Comment by lizheng-steedos** [comment]
应付合同发票只绑定合同，不绑定供应商
